"""Create tables

Revision ID: d9749277acb6
Revises: 
Create Date: 2020-05-31 17:27:20.953610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd9749277acb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mintmanga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('update_date', sa.Date(), nullable=True),
    sa.Column('chapters', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('number_of_chapters', sa.Integer(), nullable=True),
    sa.Column('new_chapters', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title'),
    sa.UniqueConstraint('url')
    )
    op.create_table('readmanga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('update_date', sa.Date(), nullable=True),
    sa.Column('chapters', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('number_of_chapters', sa.Integer(), nullable=True),
    sa.Column('new_chapters', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title'),
    sa.UniqueConstraint('url')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('tracking_mintmanga',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mintmanga_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mintmanga_id'], ['mintmanga.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('tracking_readmanga',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('readmanga_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['readmanga_id'], ['readmanga.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracking_readmanga')
    op.drop_table('tracking_mintmanga')
    op.drop_table('user')
    op.drop_table('readmanga')
    op.drop_table('mintmanga')
    # ### end Alembic commands ###
