"""added new_chapters in Tracking

Revision ID: 2e5f8d2848ab
Revises: fb734d3da06e
Create Date: 2020-05-15 17:56:14.593900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e5f8d2848ab'
down_revision = 'fb734d3da06e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracking', sa.Column('new_chapters', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracking', 'new_chapters')
    # ### end Alembic commands ###
