"""added tracking

Revision ID: 37ef818f086e
Revises: c55b47430cd5
Create Date: 2020-05-12 19:19:28.657072

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37ef818f086e'
down_revision = 'c55b47430cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manga_id', sa.Integer(), nullable=True),
    sa.Column('update_date', sa.String(), nullable=True),
    sa.Column('chapters', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('number_of_chapters', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_manga_id'), 'tracking', ['manga_id'], unique=False)
    op.drop_column('manga', 'genre_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manga', sa.Column('genre_list', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tracking_manga_id'), table_name='tracking')
    op.drop_table('tracking')
    # ### end Alembic commands ###
