"""added user_id to Subscribers

Revision ID: 76c927aeaad3
Revises: 9b0b99177b68
Create Date: 2020-05-12 22:18:09.021951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c927aeaad3'
down_revision = '9b0b99177b68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'subscribers', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscribers', type_='unique')
    op.drop_column('subscribers', 'user_id')
    # ### end Alembic commands ###
