"""rename manga_tracking to tracking_list

Revision ID: 9b0b99177b68
Revises: f51c327b66eb
Create Date: 2020-05-12 20:48:28.462191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b0b99177b68'
down_revision = 'f51c327b66eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('tracking_list', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('subscribers', 'manga_tracking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('manga_tracking', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('subscribers', 'tracking_list')
    # ### end Alembic commands ###
