"""added date column

Revision ID: e57fd170f395
Revises: 37ef818f086e
Create Date: 2020-05-12 19:24:06.980688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e57fd170f395'
down_revision = '37ef818f086e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
