"""added username to Subscribers

Revision ID: fb734d3da06e
Revises: 76c927aeaad3
Create Date: 2020-05-12 22:40:55.145127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb734d3da06e'
down_revision = '76c927aeaad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribers', 'username')
    # ### end Alembic commands ###
